#!/usr/bin/env node
// Build: (1) bundle the widget bridge, inline shared CSS/JS + bridge into each ui/*.html,
// emit src/generated/ui.ts; (2) bundle src/stdio.ts -> dist/index.js (unless --ui-only).
import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const uiOnly = process.argv.includes("--ui-only");
const WIDGETS = { overview: "overview.html", "collection-card": "collection-card.html", similarity: "similarity.html", explorer: "explorer.html" };

const bridge = await build({
  entryPoints: [join(root, "ui/bridge.ts")],
  bundle: true, format: "iife", platform: "browser", target: "es2020", write: false, minify: true, legalComments: "none",
});
const bridgeJs = bridge.outputFiles[0].text;
const sharedCss = readFileSync(join(root, "ui/shared.css"), "utf8");
const sharedJs = readFileSync(join(root, "ui/shared.js"), "utf8");

const html = {};
for (const [name, file] of Object.entries(WIDGETS)) {
  const page = readFileSync(join(root, "ui", file), "utf8");
  // Replacer functions: literal insertion (a plain string replacement would interpret `$&` etc. inside bundled code).
  html[name] = page.replace("/*@shared-css*/", () => sharedCss).replace("/*@shared-js*/", () => sharedJs).replace("/*@bridge*/", () => bridgeJs);
}
mkdirSync(join(root, "src/generated"), { recursive: true });
const ts = `// Generated by scripts/build.mjs — do not edit.\nexport const WIDGET_HTML: Record<string, string> = ${JSON.stringify(html, null, 2)};\n`;
writeFileSync(join(root, "src/generated/ui.ts"), ts);
console.log(`generated src/generated/ui.ts (${Object.keys(html).length} widgets)`);

if (!uiOnly) {
  await build({
    entryPoints: [join(root, "src/stdio.ts")],
    outfile: join(root, "dist/index.js"),
    bundle: true, platform: "node", format: "esm", target: "node20", minify: true, sourcemap: false, legalComments: "none",
    banner: { js: "#!/usr/bin/env node\nimport { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);" },
    logLevel: "warning",
  });
  console.log("bundled dist/index.js");
}
